name: coinpal
description: A Flutter crypto wallet app with Firebase and Bitcoin
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.30.0

  bitcoin_flutter:
    git:
      url: https://github.com/speramusinc/bitcoin_flutter.git
      ref: null-safety

  qr_flutter: ^4.1.0
  bip39: ^1.0.6
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/images/
