name: Coinpal
description: A Flutter crypto wallet app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core
  firebase_core: ^2.30.0

  # Firebase plugins tambahan (aktifkan jika digunakan)
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.16.0
  firebase_storage: ^11.6.0

  # State management / utils
  provider: ^6.1.2

  # QR Code
  qr_flutter: ^4.1.0

  # Crypto & HD Wallet
  bip39: ^1.0.6
  bitcoin_flutter: ^2.0.0

  # UI/UX
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0

  # Optional: untuk backup/enkripsi
  encrypt: ^5.0.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/images/
