dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.30.0

  bitcoin_flutter:
    git:
      url: https://github.com/Aisbondeng/bitcoin_flutter.git

  qr_flutter: ^4.1.0
  bip39: ^1.0.6
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  encrypt: ^5.0.3
